### ISSUE TITLE
Myra First Issue to solve. 

### ISSUE THREAD

**Issue by dagreatcode** [dagreatcode/GADZ#122]
This is just practice. This is me putting an issue or a needed feature for user experience for you to see. This is where you as an admin can create a ticket. Only the admin can create an issue or have a GitHub account connected. @Bossiana 
![Dispatcher-2-1984023525](https://github.com/dagreatcode/GADZ/assets/68244017/bed84fac-54a8-446b-9219-2bb53ae707fb)

**Comment by dagreatcode** [comment]
Please close this issue when you have made your way around. It's not too much to see here. @Bossiana

**Comment by Bossiana** [comment]
Ok, am I really supposed to close it out? This is just practice. So example, I would not details and say issue resolved, ticket closing as of 4/6/24. Then place this in the close status?

**Comment by dagreatcode** [comment]
You don't have to close. Really just know how to create them. But close this one for practice

**Comment by dagreatcode** [comment]
Oh looks like you closed it already. Way to go. Awesome
