### ISSUE TITLE
Work on the wiki website with Mira.

### ISSUE THREAD

**Issue by dagreatcode** [dagreatcode/GADZ#129]
Shamira to enter terminology information for key word search. (Pending)
11/16/203 Note: Will review google word search list to draft up information for website.

Vincent to cover what the Wiki looks like for GADZ Connect (TBD)

See "Key Word Search tab" (In Progress Queue)

**Comment by dagreatcode** [comment]
I will go ahead and add the keywords from the "Key Word Search" tab and close this and that case when I am done. @Bossiana

**Comment by dagreatcode** [comment]
We will talk more about the wiki real soon. I am setting them up. I have a Developer one and an Employee one. We may need an Admin one as well.

**Comment by Bossiana** [comment]
Date 10/30/24 - Do I have any additional task to this? Is there anything else I need to compile for the Wiki? @dagreatcode

**Comment by dagreatcode** [comment]
@Bossiana we should be done here. I've already added some content. We will finalize the wiki once we come back around to it. Thanks. The README.md looks good also. We can move to the next thing for now.

**Comment by dagreatcode** [comment]
I'm closing this issue/case.
